I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 206, in script
    scene youdied with dissolve(3.0)
TypeError: 'Dissolve' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 206, in script
    scene youdied with dissolve(3.0)
  File "C:\Users\cata7\Desktop\Local Projects\renpy-8.0.2-sdk\renpy\ast.py", line 1658, in execute
    renpy.exports.with_statement(trans, paired=paired)
  File "C:\Users\cata7\Desktop\Local Projects\renpy-8.0.2-sdk\renpy\exports.py", line 1653, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "C:\Users\cata7\Desktop\Local Projects\renpy-8.0.2-sdk\renpy\display\core.py", line 2798, in do_with
    return self.interact(trans_pause=True,
  File "C:\Users\cata7\Desktop\Local Projects\renpy-8.0.2-sdk\renpy\display\core.py", line 3377, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs) # type: ignore
  File "C:\Users\cata7\Desktop\Local Projects\renpy-8.0.2-sdk\renpy\display\core.py", line 3746, in interact_core
    trans = self.ongoing_transition[None](
TypeError: 'Dissolve' object is not callable

Windows-10-10.0.22000 AMD64
Ren'Py 8.0.2.22081402
My Discharge Diary 1.0
Mon Sep  5 22:36:06 2022
